#name: Deploy to GitHub Pages

on:
  push:
<<<<<<< HEAD
    branches: 'main'
=======
    branches: "main"
>>>>>>> a783f7b (Version 0.9)

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
<<<<<<< HEAD
          BASE_PATH: '/${{ github.event.repository.name }}'
=======
          BASE_PATH: "/${{ github.event.repository.name }}"
>>>>>>> a783f7b (Version 0.9)
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
<<<<<<< HEAD
          path: 'build/'
=======
          path: "build/"
>>>>>>> a783f7b (Version 0.9)

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
